language: python

python: 2.7

sudo: false

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
    - os: linux
      env: TOX_ENV=py27-recent-libcurl
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

before_script:
  - |
    mkdir $HOME/curl_files
    cd $HOME/curl_files
    pwd
    wget https://curl.haxx.se/download/curl-7.59.0.tar.gz
    tar -xzf curl-7.59.0.tar.gz
    cd curl-7.59.0
    ./configure --prefix=$HOME/curl_lib
    make
    make install

script:
  - apt-get remove python-pycurl python3-pycurl
  - apt-get install -y libcurl4-openssl-dev
  - python -m pip install --no-binary=pycurl -U pycurl
  - LD_LIBRARY_PATH="$HOME/curl_lib/lib" python -c 'import pycurl; print(pycurl.version)'
