language: python

python: 2.7

sudo: required

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
    - os: linux
      env: TOX_ENV=py27-recent-libcurl
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

# Enable extra mongodb and redis services on linux
# Mysql and postgres services are enabled on linux by default
# That does not work on osx (see below custom instructions for osx)
#services:
#  - mongodb
#  - redis-server

before_script:
  #- mysql -u root -e 'create database grab_test'
  #- psql -U postgres -c 'create database grab_test'
  ## Override test settings with travis settings 
  #- |
  #  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  #    cp travis_linux_settings.py test_settings_local.py
  #  else
  #    cp travis_osx_settings.py test_settings_local.py
  #  fi
  - pwd
  - |
    mkdir $HOME/curl_files
    cd $HOME/curl_files
    pwd
    wget https://curl.haxx.se/download/curl-7.59.0.tar.gz
    tar -xzf curl-7.59.0.tar.gz
    cd curl-7.59.0
    ./configure --prefix=$HOME/curl_lib
    make
    make install
  - python -m pip install -U pip setuptools tox

script:
  #- LD_LIBRARY_PATH="$HOME/curl_lib/lib" pip install pycurl
  #- ls -l $HOME/curl_lib/lib
  #- python -c 'import pycurl; print(pycurl.version)'
  #- LD_LIBRARY_PATH="$HOME/curl_lib/lib" python -c 'import pycurl; print(pycurl.version)'
  #- LD_RUN_PATH="$HOME/curl_lib/lib" python -c 'import pycurl; print(pycurl.version)'
  #- export LD_LIBRARY_PATH="$HOME/curl_lib/lib"
  #- echo $LD_LIBRARY_PATH
  #- python -c 'import pycurl; print(pycurl.version)'
  - cd $HOME/build/lorien/grab
  - LD_LIBRARY_PATH="/curl_lib/lib" tox -e $TOX_ENV

#after_success:
#  - coveralls
